### ISSUE TITLE
The MapView does not get resolved

### ISSUE THREAD

**Issue by sruthisripathi** [nicksenger/react-arcgis#42] opened 2018-02-20 11:08 UTC
Hi,
Refering to this react-arcgis repo. I wrote the following component to render basemap.

`import React, { Component } from 'react';
import { loadModules } from 'esri-loader';

class BaseMap extends Component {
  constructor(props) {
    super(props);

    this.state = {
      mapContainerId: 'basemap',
      status: 'loading'
    }
  }
  componentDidMount() {
    loadModules(['esri/Map', 'esri/views/MapView'])
    .then(([Map, View]) => {
      const map = new Map(this.props.mapProperties);
      const viewProperties = {
        map,
        container: this.state.mapContainerId,
        ...this.props.viewProperties
      };
      const rView = new View(viewProperties);
      rView.then((view) => {
        this.setState({
          map,
          view,
          status: 'loaded'
        });
      })
      .catch((e) => {
        this.setState({ status: 'failed' });
        throw e;
      })
    })
    .catch((e) => {
      this.setState({ status: 'failed' });
      throw e;
    })
  }

  render() {
    if (this.state.status === 'loaded') {
      return (
        <div id={this.state.mapContainerId} style={{ width: '100%', height: '100%' }}></div>
      );
    }
    else if(this.state.status === 'loading') {
      return (
        <div>Loading</div>
      );
    }
    else {
      return (
        <div>Failed loading map</div>
      );
    }
  }
}

export default BaseMap;
`

But the status does not change to loaded. It is stuck at loading. 
On debugging I found that the MapView promise inside componentDidMount() function is not getting resolved. It's not going into the catch block too. It is stuck there. 

I also tried using the BaseMap component you provided in react-arcgis

`import React, { Component } from 'react';
import { Map } from 'react-arcgis';
export default class App extends Component {
  render() {
    return (
      <div>
        <Map />
      </div>
    );
  }
}
`

But no map is loaded. Initially I can see loading after that the div remains just blank.
The map loaded after I wrapped it inside a div like this
`            <div style={{ width: '100vw', height: '100vh' }}>
                <Map />
            </div>`

**Comment by nicksenger** [comment] 2018-02-23 21:27
@sruthisripathi This is similar to the other issue that you opened, and react-arcgis is working as intended here. The `<Map />` , `<Scene />`, `<WebMap />` and `<WebScene />`  components from react-arcgis merely fill their parent container by default.

I'm not sure what's going wrong with the component you've written, but it does not use anything from react-arcgis. Is there a reason you don't want to use `<Map />` in this case?

**Comment by nicksenger** [comment] 2018-02-23 21:28
Closing for now as react-arcgis seems to be working as designed.

**Closed by nicksenger** 2018-02-23 21:28 UTC
